apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: dev-forum-api
          command: ["supervisord", "-n"]
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
       
